// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsP5eJ8vzjX3KPLj9d5_rzh-axoXKZ_-M',
    appId: '1:844874502875:web:a82d56c87604a64ee572fe',
    messagingSenderId: '844874502875',
    projectId: 'movieticketbooking-d2a73',
    authDomain: 'movieticketbooking-d2a73.firebaseapp.com',
    storageBucket: 'movieticketbooking-d2a73.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDY3DHWBoiy7b9TQeRugj1DijCdlBxO4s',
    appId: '1:844874502875:android:1a2542b8229b49f1e572fe',
    messagingSenderId: '844874502875',
    projectId: 'movieticketbooking-d2a73',
    storageBucket: 'movieticketbooking-d2a73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKsAcviIXtHwSvHSkReAegCG73jymja4Q',
    appId: '1:844874502875:ios:ce5284ebd5d8c330e572fe',
    messagingSenderId: '844874502875',
    projectId: 'movieticketbooking-d2a73',
    storageBucket: 'movieticketbooking-d2a73.appspot.com',
    iosBundleId: 'com.example.movieTicketBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKsAcviIXtHwSvHSkReAegCG73jymja4Q',
    appId: '1:844874502875:ios:e9cf4160bfa461a9e572fe',
    messagingSenderId: '844874502875',
    projectId: 'movieticketbooking-d2a73',
    storageBucket: 'movieticketbooking-d2a73.appspot.com',
    iosBundleId: 'com.example.movieTicketBooking.RunnerTests',
  );
}
